blank_issues_enabled: false
contact_links:
  - name: Questions & Discussions
    url: https://github.com/hasnaintypes/shopra-monorepo/discussions
    about: Please use GitHub Discussions for general questions and conversations.
