name: CI

on:
  push:
    branches: [develop, master]
  pull_request:
    branches: [develop, master]

env:
  COREPACK_ENABLE_STRICT: 0

jobs:
  install-and-check:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false

      - name: Setup Node.js with pnpm cache
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Check formatting
        run: pnpm format:check

      - name: Lint code
        run: pnpm lint

      - name: Run tests
        run: pnpm test:ci
